---
title: "SI_Figure4: ASVs in Field Samples"
output: html_notebook
---


```{r}
library(ggplot2)
library(phyloseq)
library(tidyverse)
library(phylosmith)
library(readr)
library(cowplot) #https://rdrr.io/cran/cowplot/man/save_plot.html
```

```{r}
#SF to HI transit samples Only
SFtoHI <- subset_samples(ps, sample_type3%in%c("field"))
SFtoHI
#Remove Bacteria and Archaea sequences and all unknown, unassigned, no hit
SFtoHI_pruneBac <- taxa_prune(SFtoHI,'tax=k__Bacteria','Kingdom')
SFtoHI_pruneProk <- taxa_prune(SFtoHI_pruneBac,'tax=k__Archaea','Kingdom')
SFtoHI_pruneProkUnk <- taxa_prune (SFtoHI_pruneProk,'tax=k__unassigned','Kingdom')
SFtoHI_pruneProkUnk <- taxa_prune (SFtoHI_pruneProkUnk,'tax=k__unknown','Kingdom')
SFtoHI_pruneProkUnk <- taxa_prune (SFtoHI_pruneProkUnk,'tax=k__no_hit','Kingdom')

SFtoHI_pruneProkUnk <- prune_taxa(taxa_sums(SFtoHI_pruneProkUnk) > 0,SFtoHI_pruneProkUnk)

get_taxa_unique(SFtoHI_pruneProk, "Kingdom")
get_taxa_unique(SFtoHI_pruneProkUnk, "Kingdom")
get_taxa_unique(SFtoHI_pruneProkUnk, "Phylum")
ntaxa(SFtoHI_pruneProkUnk)

#removes the taxa level assignments for the phyla for plotting
tax_table(SFtoHI)[, colnames(tax_table(SFtoHI))] <- gsub(tax_table(SFtoHI)[, colnames(tax_table(SFtoHI))],     pattern = "tax=", replacement = "")
tax_table(SFtoHI)[, colnames(tax_table(SFtoHI))] <- gsub(tax_table(SFtoHI)[, colnames(tax_table(SFtoHI))],     pattern = "[a-z]__", replacement = "")

tax_table(SFtoHI_pruneProkUnk)[, colnames(tax_table(SFtoHI_pruneProkUnk))] <- gsub(tax_table(SFtoHI_pruneProkUnk)[, colnames(tax_table(SFtoHI_pruneProkUnk))],     pattern = "tax=", replacement = "")
tax_table(SFtoHI_pruneProkUnk)[, colnames(tax_table(SFtoHI_pruneProkUnk))] <- gsub(tax_table(SFtoHI_pruneProkUnk)[, colnames(tax_table(SFtoHI_pruneProkUnk))],     pattern = "[a-z]__", replacement = "")

daynightcolor = c("orange","black", "blue")

p1 <- plot_richness(SFtoHI_pruneProkUnk, x="LongitudeStart", measures=c("Chao1"),color= "daynight") +
  scale_x_discrete(lim=rev) +
  scale_color_manual(values = daynightcolor) +
  labs(x="Longitude",y="Alpha Diversity Measure") +
  theme (
    legend.text = element_text(colour="black", size=10),
    axis.ticks = element_line( size = 0.1),
    axis.text.x = element_text(size = 6, angle = 90, vjust = 0.5, hjust=1),
    axis.line = element_line(size=0.1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white",
                                colour = "white",
                                size = 0.5, linetype = "solid"),
    legend.key=element_blank()
  )

p2 <- plot_richness(SFtoHI_pruneProkUnk, x="LongitudeStart", measures=c("Observed"),color= "daynight") +
  scale_x_discrete(lim=rev) +
  scale_color_manual(values = daynightcolor) +
  labs(x="Longitude",y="Alpha Diversity Measure") +
  theme (
    legend.text = element_text(colour="black", size=10),
    axis.ticks = element_line( size = 0.1),
    axis.text.x = element_text(size = 6, angle = 90, vjust = 0.5, hjust=1),
    axis.line = element_line(size=0.1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white",
                                colour = "white",
                                size = 0.5, linetype = "solid"),
    legend.key=element_blank()
  )

p3 <- plot_richness(SFtoHI_pruneProkUnk, x="LongitudeStart", measures=c("Shannon"),color= "daynight") +
  scale_x_discrete(lim=rev) +
  scale_color_manual(values = daynightcolor) +
  labs(x="Longitude",y="Alpha Diversity Measure") +
  theme (
    legend.text = element_text(colour="black", size=10),
    axis.ticks = element_line( size = 0.1),
    axis.text.x = element_text(size = 6, angle = 90, vjust = 0.5, hjust=1),
    axis.line = element_line(size=0.1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white",
                                colour = "white",
                                size = 0.5, linetype = "solid"),
    legend.key=element_blank()
  )
  p1
  p2
  p3
  

FigureSI_field <- plot_grid (p1, p3,
           align ="v",
           labels = "", 
           axis = "b",
           ncol = 1)

FigureSI_field

save_plot(
  filename = "figs/FigSI4_field.eps",
  plot = FigureSI_field ,
  ncol = 1,
  nrow = 3,
  base_height = 3.71,
  base_asp = 1.68)
 
  
  
  
```

```{r}
#https://forum.qiime2.org/t/exporting-otu-table-from-phyloseq-into-either-biom-or-text-format/19103/6
write_biom_csv <- function(ps, file, sep = "; ") {
  phyloseq::otu_table(ps) %>%
    as.data.frame() %>%
    rownames_to_column("#OTU ID") %>%
    left_join(phyloseq::tax_table(ps) %>% 
                as.data.frame() %>%
                rownames_to_column("#OTU ID") %>% 
                tidyr::unite("taxonomy", !`#OTU ID`, sep = sep)) -> phyloseq_biom
  
  write_tsv(phyloseq_biom, file = file)
}

write_biom_csv (SFtoHI,file="tables/SFtoHIfield_all.csv")
write_biom_csv (SFtoHI_pruneProkUnk,file="tables/SFtoHIfield.csv")

#Tally for determining how many ASVs.  
#Includes Bacteria, Archea, no hits
fieldASV_all <- read.table("tables/SFtoHIfield_all.csv",sep="\t", header=T, comment="")
fieldASV_all <- fieldASV_all %>% separate(taxonomy, c("Kingdom","Phylum","Class","Order","Family","Genus","Species"))
fieldASV_all$sumASV <- rowSums(fieldASV_all[,c(2:53)])
fieldASV_all <- fieldASV_all[fieldASV_all$sumASV !=0, ]
fieldASV_all
fieldASV_allEuk <- fieldASV_all[fieldASV_all$Kingdom=='Eukaryota',]
fieldASV_allEuk
unique(fieldASV_allEuk$Phylum)
fieldASV_allEuk_assigned <- fieldASV_allEuk[!fieldASV_allEuk$Phylum=='unassigned',]
fieldASV_allEuk_assigned

#fieldASV from SFtoHI_pruneProkUnk 
fieldASV <- read.table("tables/SFtoHIfield.csv",sep="\t", header=T, comment="")
fieldASV <- fieldASV %>% separate(taxonomy, c("Kingdom","Phylum","Class","Order","Family","Genus","Species"))
fieldASV$sumASV <- rowSums(fieldASV[,c(2:53)])
fieldASV

#All ASVs assigned to Eukarya
fieldASV <- fieldASV[fieldASV$sumASV !=0, ]
fieldASV
fieldASVassigned <- fieldASV[!fieldASV$Phylum=='unassigned',]
fieldASVassigned
write.table(fieldASVassigned, file = "tables/fieldASVassigned.txt", sep = ",", quote = FALSE, row.names = F)

fieldASVassigned <-  subset (fieldASVassigned, select = -c(X.OTU.ID,Kingdom,Class,Order,Family,Genus,Species))
summaryfieldASVassigned <- fieldASVassigned %>%
  group_by(Phylum) %>%
  dplyr::summarise(across(everything(), list(sum)))
summaryfieldASVassigned
write.table(summaryfieldASVassigned, file = "tables/summaryfieldASVassigned.txt", sep = ",", quote = FALSE, row.names = F)


#SF Bay - ESP135,ESP136,ESP137
#Number of ASVs assigned to Phylum
SFbay <- subset (fieldASV, select = c(X.OTU.ID,ESP135,ESP136,ESP137,Kingdom,Phylum))
SFbay
#sum all ASVs then remove all ASVs not in any sample.
SFbay$sumASV <- rowSums(SFbay[,c(2:4)])
SFbay <- SFbay[SFbay$sumASV !=0, ]
SFbay
unique(SFbay$Phylum)
SFbay <- SFbay[!SFbay$Phylum=='unassigned',]
SFbay
unique(SFbay$Phylum)

SFbaySum <-  subset (SFbay, select = -c(X.OTU.ID,Kingdom))
SFbaySum <- SFbaySum %>%
  group_by(Phylum) %>%
  dplyr::summarise(across(everything(), list(sum)))
SFbaySum
write.table(SFbaySum, file = "tables/SFbay.txt", sep = ",", quote = FALSE, row.names = F)


#Pacific Ocean
PacOcean <-  subset (fieldASV, select = -c(ESP135,ESP136,ESP137))
#sum all ASVs then remove all ASVs not in any sample.
PacOcean$sumASV <- rowSums(PacOcean[,c(2:50)])
PacOcean <- PacOcean[PacOcean$sumASV !=0, ]
PacOcean
unique(PacOcean$Phylum)
PacOcean <- PacOcean[!PacOcean$Phylum=='unassigned',]
PacOcean
unique(PacOcean$Phylum)
write.table(PacOcean, file = "tables/PacificOcean_ASVs.txt", sep = ",", quote = FALSE, row.names = F)

PacOceanSum <-  subset (PacOcean, select = -c(X.OTU.ID,Kingdom,Class,Order,Family,Genus,Species))
PacOceanSum <- PacOceanSum %>%
  group_by(Phylum) %>%
  dplyr::summarise(across(everything(), list(sum)))
PacOceanSum
write.table(PacOceanSum, file = "tables/PacificOcean.txt", sep = ",", quote = FALSE, row.names = F)


#Pivot to plot 
ASVs_all <- fieldASV%>%
  pivot_longer(cols = starts_with("ESP"), names_to = "eDNAsample", values_to = "ASVcounts") %>% 
  group_by(eDNAsample) %>%
  summarise(ASVs_all = length( which(ASVcounts>0)))
ASVs_all

#ASVs > 25 sequences
fieldASV25 <-fieldASV[fieldASV$sumASV >25, ]
fieldASV25

ASVs_25 <- fieldASV25%>%
  pivot_longer(cols = starts_with("ESP"), names_to = "eDNAsample", values_to = "ASVcounts") %>% 
  group_by(eDNAsample) %>%
  summarise(ASVs_25 = length( which(ASVcounts>0)))
ASVs_25

#ASVs > 50 sequences
fieldASV50 <-fieldASV[fieldASV$sumASV >50, ]
fieldASV50 

ASVs_50 <- fieldASV50%>%
  pivot_longer(cols = starts_with("ESP"), names_to = "eDNAsample", values_to = "ASVcounts") %>% 
  group_by(eDNAsample) %>%
  summarise(ASVs_50 = length( which(ASVcounts>0)))
ASVs_50

#Put all of the tables together
df_list <- list(ASVs_all, ASVs_25, ASVs_50) 
df <- df_list %>% reduce(full_join, by='eDNAsample')
df
 
df <- df %>%
pivot_longer (cols = starts_with("ASV"), names_to = "counts", values_to = "ASVcounts") %>% 
  group_by(eDNAsample)
df

df$counts <- as.factor(df$counts)
df$eDNAsample <- as.factor(df$eDNAsample)
df$counts <- factor(df$counts, levels = c("ASVs_all","ASVs_25","ASVs_50","Shannon", "Chao1"))
df

customFill = c("black","blue","lightblue")

LonLabelOrder2si = c("-156.58","-156.39","-156.20","-156.01","-155.82","-155.63","-152.01","-151.44","-150.55","-149.67","-148.86","-148.44","-147.50","-146.89","-146.08","-145.37","-144.49","-143.96","-143.61","-142.85","-142.04","-141.10","-140.15","-139.06","-138.29","-137.62","-137.02","-136.37","-135.54","-134.58","-133.87","-133.15","-132.29","-131.43","-130.59","-129.73","-128.76","-128.09","-127.14","-126.89","-126.25","-125.71","-125.36","-124.64","-124.42","-124.33","-123.76","-122.91","-122.62","-122.48","-122.40","-122.34")

LonLabelOrder2si_lim = c("-156.58","","","","","","","","","","","","","","","","","","","","","","","","","","-137.02","","","","","","","","","","","","","","","","","","","","","","","","","-122.34")

countsOrder_label = c("All ASVs", "ASVs >25 sequences","ASVs >50 sequences")

p <- ggplot (df,aes(x = eDNAsample, y = ASVcounts, fill = counts)) + 
  geom_point (pch = 21) +
  scale_fill_manual(values = customFill, labels = countsOrder_label) +
  labs(x="eDNA sample",y="Number of ASVs") +
  theme(axis.text.x = element_text(size = 6, angle = 90, vjust = 0.5, hjust=1)) +
  theme(aspect.ratio=1)+
  scale_x_discrete(lim=rev,labels = LonLabelOrder2si) +
  ylim(1,1250) +
  guides(fill=guide_legend(title="ASVs")) +
  theme (
    legend.text = element_text(colour="black", size=10),
    axis.ticks = element_line( size = 0.1),
    axis.text.x = element_text(size = 6, angle = 90, vjust = 0.5, hjust=1),
    axis.line = element_line(size=0.1),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "white",
                                colour = "white",
                                size = 0.5, linetype = "solid"),
    legend.key=element_blank()
  )
p

ggsave(file="figs/SI_NumberASVs.pdf", plot=p, dpi=600)
```
```


